# Page settings

baseurl = "https://markussommerfeld-cv.netlify.com/"
languageCode = "en-us"
title = "Markus Sommerfeld Resume"
theme = "hugo-orbit-theme"
googleAnalytics = "UA-XXXXXXX-Y"

# Do not build files for websites. Need them? Set to false
disableRSS = true
disableSitemap = true
disable404 = true

[params]

# Meta
    description = "Hugo Responsive Resume/CV Theme for Developers"
    author = "Pavel Kanyshev"

# Theme styles

    # The original template comes with 6 colour schemes. You may choose styles below.
    # "styles.css", "styles-2.css", "styles-3.css", "styles-4.css", "styles-5.css", "styles-6.css"
    # are available. Also the source LESS files are included so
    # it’s quick and easy to change the styling and colour scheme.

    styles = "styles.css"

# Sidebar sections

    # Profile section
    [params.profile]
        name = "Markus Sommerfeld"
        tagline = "Futurist and Engineer"
        avatar = "profile.png"

    # Contact section
    [params.contact]
        enable = true

        [[params.contact.list]]
        class = "email"
        icon = "fa-envelope"
        url = "mailto: msommerf@uvic.ca"
        title = "msommerf@uvic.ca"

        [[params.contact.list]]
        class = "phone"
        icon = "fa-phone"
        url = "tel:+1234567890"
        title = "+1234567890"

        [[params.contact.list]]
        class = "website"
        icon = "fa-globe"
        url = "https://markussommerfeld-academic.netlify.com/"
        title = "markussommerfeld-academic.com"

        [[params.contact.list]]
        class = "linkedin"
        icon = "fa-linkedin"
        url = "https://www.linkedin.com/in/markus-sommerfeld/"
        title = "linkedin.com/in/markus-sommerfeld/"

        [[params.contact.list]]
        class = "github"
        icon = "fa-github"
        url = "https://github.com/markussommerfeld"
        title = "github.com/markussommerfeld"

        [[params.contact.list]]
        class = "twitter"
        icon = "fa-twitter"
        url = "https://twitter.com/Dudegoesplaces"
        title = "@Dudegoesplaces"
		
		[[params.contact.list]]
        class = "researchgate"
        icon = "fa-researchgate"
        url = "https://www.researchgate.net/profile/Markus_Sommerfeld"
        title = "https://www.researchgate.net/profile/Markus_Sommerfeld"
		
		 

    # Education section
    [params.education]
        enable = true
        title = "Education"

		[[params.education.list]]
        degree = "PhD in Mechanical Engineering"
        college = "University of Victoria, BC Canada"
        dates = "2015 - 2020"
		
        [[params.education.list]]
        degree = "Dipl.-Ing. in Mechanical Engineering"
        college = "Technical University Kaiserslautern, Germany"
        dates = "2008 - 2014"
		
        [[params.education.list]]
        degree = "Abitur"
        college = "Paul Schneider Gymnasium, Meisenheim, Germany"
        dates = "1997 - 2007"

    # Languages section
    #[params.language]
    #   enable = true
	#       title = "Languages"
	#
    #    [[params.language.list]]
    #    language = "German"
    #    level = "5"

    #    [[params.language.list]]
    #    language = "English"
    #    level = "4"

    #    [[params.language.list]]
    #    language = "Japanese"
    #    level = "2"

    #    [[params.language.list]]
    #    language = "French"
    #    level = "2"

    # Interests section
    [params.interests]
        enable = true
        title = "Interests"

        [[params.interests.list]]
        interest = "Crossfit"

        [[params.interests.list]]
        interest = "Technology"

        [[params.interests.list]]
        interest = "Cooking"

# Main body sections

    # You may use markdown in summary, details and intro fields. But don't overdose, it's resume!:)

    # Summary section
    [params.summary]
        enable = true
        icon = "fa-user"
        title = "Career Profile"
        summary = ""

    # Experiences section
    [params.experiences]
        enable = true
        icon = "fa-briefcase"
        title = "Experiences"

        [[params.jobs.list]]
        position = "PhD"
        dates = "2015 - 2020"
        company = "University of Victoria, BC Canada"
        details = "In my PhD research at the University of Victoria, Canada I determine the wind 
					energy  potential  of  tall  wind  turbines  and  innovative  new  airborne  wind  energy 
					systems.  Through  collaboration  with  international  research  institutes,  universities 
					and companies I developed competence in LiDAR measurement technologies, wind 
					modeling,  optimization  and  data  analysis.  I  acquired  technical  certification  and 
					testing experience according to international standards through work experiences in 
					Japan  and  Germany.  I  am  competent  in  tackling  administrative  tasks  and  work 
					efficiently  in  multi-cultural  teams  to  achieve  scientific  excellence  and  client 
					satisfaction."

        [[params.jobs.list]]
        position = "Senior Software Engineer"
        dates = "2015"
        company = "Fraunhofer IWES, Bremerhaven Germany"
        details = "**Describe your role here** lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem."

        [[params.jobs.list]]
        position = "UI Developer"
        dates = "2012 - 2014"
        company = "Amazon, London"
        details = "**Describe your role here** lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem."

    # Projects section
    [params.projects]
        enable = true
        icon = "fa-archive"
        title = "Random Text"
        intro = "**You can list your side projects or open source libraries in this section.** Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum et ligula in nunc bibendum fringilla a eu lectus"

        [[params.projects.list]]
        title = "Master Thesis"
        url = "https://github.com/aerohub/hugrid"
        tagline = "Grid theme for Hugo. It's a kind of boilerplate to perform anyone or anything quickly. Portfolio, collection, bookmarks, contacts and so on"

        [[params.projects.list]]
        title = "Simple FAQ Theme for Hugo"
        url = "https://github.com/aerohub/hugo-faq-theme"
        tagline = "Simple FAQ Theme for Hugo. You may use this theme for building very simple FAQs or note lists."

        [[params.projects.list]]
        title = "Hugo Identity"
        url = "https://github.com/aerohub/hugo-identity-theme"
        tagline = "Little profile/card-style template for Hugo."

        [[params.projects.list]]
        title = "Orbit"
        url = "https://github.com/aerohub/hugo-orbit-theme"
        tagline = "Hugo Resume/CV Theme for Developers."

        [[params.projects.list]]
        title = "Me"
        url = "https://github.com/aerohub/hugo-me-theme"
        tagline = "A simple responsive Hugo theme for personal site."
 
	# Publication section
    [params.publications]
	enable = true
	icon = "fa-newspaper-o"
	title = "Publications"
	intro = "**You can list your side projects or open source libraries in this section.** Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum et ligula in nunc bibendum fringilla a eu lectus"
   
    [[params.publications.list]]
	title = "LiDAR-based characterization of mid-altitude wind conditions for airborne wind energy systems"
	url = "https://doi.org/10.1002/we.2343"
	tagline = ""
	
    [[params.publications.list]]
	title = "Improving mesoscale wind speed forecasts using lidar-based observation nudging for airborne wind energy systems"
	url = "https://doi.org/10.5194/wes-4-563-2019"
	tagline = ""

	# Presentation section
    #[params.presentations]
	#enable = true
	#icon = "fa-presentation"
	#title = "Presentations"
	#intro = "**You can list your side projects or open source libraries in this section.** Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum et ligula in nunc bibendum fringilla a eu lectus"

    [[params.presentations.list]]
        title = "Hugrid"
        url = "https://github.com/aerohub/hugrid"
        tagline = "Grid theme for Hugo. It's a kind of boilerplate to perform anyone or anything quickly. Portfolio, collection, bookmarks, contacts and so on"

    # Skills section
    [params.skills]
        enable = true
        icon = "fa-rocket"
        title = "Skills & Proficiency"

        [[params.skills.list]]
        skill = "Python & Django"
        level = "98%"
                
        [[params.skills.list]]
        skill = "Javascript & jQuery"
        level = "98%"

        [[params.skills.list]]
        skill = "Angular"
        level = "95%"

        [[params.skills.list]]
        skill = "HTML5 & CSS"
        level = "95%"

        [[params.skills.list]]
        skill = "Ruby on Rails"
        level = "75%"

        [[params.skills.list]]
        skill = "Sketch & Photoshop"
        level = "60%"

    # Footer section

    # The original template is released under the Creative Commons Attribution 3.0 License.
    # Please keep the original attribution link when using for your own project.
    # If you'd like to use the template without the attribution,
    # you can check out other license options via template author's website: themes.3rdwavemedia.com
    # 
    # As for Hugo port you may rewrite the "Ported for..." line with setting your name below.

    [params.footer]
        copyright = ""
