# Page settings

baseurl = "https://markussommerfeld-cv.netlify.com/"
languageCode = "en-us"
title = "Markus Sommerfeld Resume"
theme = "hugo-orbit-theme"
googleAnalytics = "UA-XXXXXXX-Y"

# Do not build files for websites. Need them? Set to false
disableRSS = true
disableSitemap = true
disable404 = true

[params]

# Meta
    description = "CV Markus Sommerfeld"
    author = "Markus Sommerfeld"

# Theme styles

    # The original template comes with 6 colour schemes. You may choose styles below.
    # "styles.css", "styles-2.css", "styles-3.css", "styles-4.css", "styles-5.css", "styles-6.css"
    # are available. Also the source LESS files are included so
    # it’s quick and easy to change the styling and colour scheme.
    
    styles = "styles.css"

# Sidebar sections

    # Profile section
    [params.profile]
        name = "Markus Sommerfeld"
        tagline = "PhD in Mechanical Engineering"
		#birthday = "3 February 1987"
		#location = "Victoria, BC, Canada"
        avatar = "profile.png"
    
    # Contact section
    [params.contact]
        enable = true
		
		# profile additional section
		[params.profile_info]
        enable = true
        title = "profile_info"		
    
        [[params.profile_info.list]]
		class = "birthday"
		icon = "fa-birthday-cake"
        title = "3 February 1987"
		
		[[params.profile_info.list]]
		class = "location"
		icon = "fa-map-marker"
        title = " Victoria, BC, Canada"
		
		#[[params.contact.list]]
        #class = "website"
        #icon = "fa-birthday-cake"
        #url = ""
        #title = "1987 February 3"
		
		#[[params.contact.list]]
        #class = "website"
        #icon = "fa-map-marked-alt"
        #url = ""
        #title = "Victoria, BC Canada"
		
    
        [[params.contact.list]]
        class = "email"
        icon = "fa-envelope"
        url = "mailto: msommerf@uvic.ca"
        title = "msommerf@uvic.ca"
    
	
	
    #    [[params.contact.list]]
    #    class = "phone"
    #    icon = "fa-phone"
    #    url = "tel:+1234567890"
    #    title = "+1234567890"
    
        [[params.contact.list]]
        #class = "website"
        #icon = "fa-globe"
        #url = "" #https://markussommerfeld-academic.netlify.com/
        #title = "markussommerfeld-academic.com"
    
        [[params.contact.list]]
        class = "linkedin"
        icon = "fa-linkedin"
        url = "https://www.linkedin.com/in/markus-sommerfeld/"
        title = "markus-sommerfeld"
    
        [[params.contact.list]]
        class = "github"
        icon = "fa-github"
        url = "https://github.com/markussommerfeld"
        title = "markussommerfeld"
    
        #[[params.contact.list]]
        #class = "twitter"
        #icon = "fa-twitter"
        #url = "https://twitter.com/Dudegoesplaces"
        #title = "@Dudegoesplaces"
    	
    	[[params.contact.list]]
        class = "researchgate"
        icon = "ai ai-researchgate ai-3x"
        url = "https://www.researchgate.net/profile/Markus_Sommerfeld"
        title = "Markus_Sommerfeld"


    # Education section
    [params.education]
        enable = true
        title = "Education"
    
    	[[params.education.list]]
        degree = "PhD in Mechanical Engineering"
        college = "University of Victoria, BC, Canada"
        dates = "2015 - 2020"
    	
        [[params.education.list]]
        degree = "Dipl.-Ing. in Mechanical Engineering"
        college = "Technical University Kaiserslautern, Germany"
        dates = "2008 - 2014"
    	
        [[params.education.list]]
        degree = "High School"
        college = "Paul Schneider Gymnasium, Meisenheim, Germany"
        dates = "1997 - 2007"
    
    # Languages section
    [params.language]
       enable = true
       title = "Languages"
    
       [[params.language.list]]
       language = "German"
       level = "5"
    
       [[params.language.list]]
       language = "English"
       level = "4"
    
       [[params.language.list]]
       language = "Japanese"
       level = "2"
    
       [[params.language.list]]
       language = "French"
       level = "2"
    
    # Interests section
    [params.interests]
        enable = true
        title = "Hobbies & Interests"		
    
        [[params.interests.list]]
        interest = "Playtime with my daughter"
		icon = "fa fa-home"

        [[params.interests.list]]
        interest = "Crossfit workouts with friends"
		icon = "fa fa-bomb"

        [[params.interests.list]]
        interest = "Learn Japanese"
		icon = "fa fa-puzzle-piece"
        
		#[[params.interests.list]]
		#interest = "Invent stuff"
		#icon = "fa fa-cogs"

		[[params.interests.list]]
		interest = "Work on website"
		icon = "fa fa-rebel"
		
		[[params.interests.list]]
        interest = "Try out vegan and vegetarian recipes"
		icon = "fa fa-cutlery"

# Main body sections

	# You may use markdown in summary, details and intro fields. But don't overdose, it's resume!:)

	# Summary section

	[params.summary]
		enable = true
		icon = "fa-user"
		title = "Career Profile"
		summary = "Master and PhD in Mechanical engineering with structure test lead experience and proven skills in wind modeling, programming, data analysis and mechanical design. <br><br>My research on airborne wind energy systems combines wind resource assessment, via <b>LiDAR</b> measurements and WRF <b>weather simulations</b>, with aircraft <b>modeling and trajectory <b>optimization</b>. Together with international teams in Germany and Japan, I planned and organized aircraft <b>structure tests</b> as well as solar PV certification projects. Working as a teaching assistant, tutor and student representative throughout my degrees made me an efficient communicator and taught me to manage my own time while supervising multiple small teams. <br><br> My goal is to use my wind energy expertise and passion for aerospace technologies to provide sustainable, affordable electricity and cleaner, more efficient means of transportation."    


	# Experiences section
	[params.experiences]
	    enable = true
	    icon = "fa-briefcase"
	    title = "Experiences"
	
	    [[params.jobs.list]]
	    position = "PhD in Mechanical Engineering"
	    dates = "2015 - 2020"
	    company = "University of Victoria, Institute for Integrated Energy Systems, Victoria BC, Canada"
	    details = "Determined the wind energy potential of innovative, new airborne wind energy systems and tall wind turbines. Collaborated with international research institutes, universities and companies. Evaluated LiDAR measurements, simulated numerical weather predictions, optimized trajectories of tethered aircraft and performed a sizing study. Published in high-impact journals and presented at international conferences and seminars."

	    [[params.jobs.list]]
	    position = "Engineering Consultant: various Projects"
	    dates = "2018 - 2020"
	    company = "University of Victoria, Institute for Integrated Energy Systems, Victoria BC, Canada"
	    details = "Consulted several start-ups and local companies about the development of novel wind energy technologies by sharing technical knowledge, assessing feasibility and performing concept studies. These projects were partially funded through NSERC Engage Grant and NRC-IRAP grants."

	
	    [[params.jobs.list]]
	    position = "Research Assistant: Wind Turbine Blade Manufacturing"
	    dates = "2015"
	    company = "Fraunhofer IWES, Bremerhaven, Germany"
	    details = "Continued working on the 'BladeMaker' project after finishing my diploma thesis. My design work and prototyping of an automated laying head contributed to the development of an automated rotor blade manufacturing process which reduces the manufacturing costs by over 10% while maintaining high production quality."
	
	  [[params.jobs.list]]
	    position = "Graduate Intern: Test Engineer"
	    dates = "2013 - 2014"
	    company = "TÜV Rheinland, Solar Energy Assessment Center, Yokohama, Japan"
	    details = "Diligently performed and evaluated certification tests of photovoltaic modules, such as hail impact tests or humidity freeze tests, according to international standards (IEC 61215, 61730 and 61646). Designed and implemented module breakage test rig. Assisted in on-site inspections and safety assessments. Calculated annual energy yield predictions for local, large-scale solar power plants and developed an uncertainty estimation to improve revenue predictions for local customers."

	   [[params.jobs.list]]
	    position = "Graduate Intern: Test and Design Engineer"
	    dates = "2012"
	    company = "Airbus Operations, Structures Test center, Hamburg, Germany"
	    details = "Independently planned, executed and analyzed component tests on CFRP A350 fuselage parts and lighting strike repair patches. Supported experienced project engineers with scheduling tests, progress tracking and data acquisition. Collaborated on the design, supervised the manufacturing and commissioned the A400M roller system test rig."
		
	    #[[params.jobs.list]]
	    #position = "Grad student representative"
	    #dates = "2016 - 2017"
	    #company = "University of  Victoria, Canada"
	    #details = "**Describe your role here** Organizational and finance committee experience"
	
	# Projects section
	[params.projects]
	    enable = true
	    icon = "fa-archive"
	    title = "Projects"
	    intro = "" #**You can list your side projects or open source libraries in this section.** Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum et ligula in nunc bibendum fringilla a eu lectus
		# This section lists up some of the lates projects I worked on.
		
	    [[params.projects.list]]
	    title = "Engineering Consultant: New Leaf"
	    url = "http://www.newleaf.co/"
	    tagline = "Consulted researchers in their development of a novel Airborne Wind Energy Ground Station and a follow-up study on Airborne Wind Energy sizing. Estimated power and mechanical tether load for various system sizes using numerical optimization based on realistic wind speed profiles. These projects were partially funded through NSERC Engage Grant and NRC-IRAP grants."

	    [[params.projects.list]]
	    title = "Engineering Consultant: Ocean Rodeo"
	    url = "https://oceanrodeo.com/"
	    tagline = "Generated concepts and designed a small-scale Airborne Wind Energy System for mobile deployment in collaboration with kite engineers and kiteboarding experts. This project was partially funded through NSERC Engage Grant and NRC-IRAP grants."

	    [[params.projects.list]]
	    title = "Teaching Assistant"
	    url = "https://www.uni-kl.de/en/"
	    tagline = "Supervised final design capstone projects. Organized and led meetings. Evaluated performance and tracked progress. Tutored engineering mechanics, fluid mechanics and wind energy tutorials as well as laboratories. Co-developed material for an online wind energy course. "
	
	    [[params.projects.list]]
	    title = "Student Assistant"
	    url = "https://www.ivw.uni-kl.de/en/home"
	    tagline = "Preparation, execution of CFRP test specimens for static load tests. FEA modeling and stress estimation of these tests."
	
	
	    [[params.projects.list]]
	    title = "Grad Student Representative"
	    url = "https://gss.uvic.ca/"
	    tagline = "Oversaw the annual budget of the Graduate Students' Society during the three year tenure as a member of the  finance committee. Planned and monitored the renovation of the university’s “Grad House” restaurant, together with other representatives, staff and managers."
	 
		[[params.projects.list]]
	    title = "Co-Founder: Entrpreneurship Playground"
	    url = "https://www.uvic.ca/innovation/"
	    tagline = "Co-founded an organization to promote student entrepreneurship. Planned several events and organized speakers together with the Coast Capital Innovation Centre. Participated and won business idea pitch competitions."
	    
		[[params.projects.list]]
	    title = "Diploma Thesis"
	    url = "https://www.iwes.fraunhofer.de/en/research-projects/finished-projects-20171/blademaker.html"
	    tagline = "Developed, designed and commissioned a carbon fiber roving impregnation device for the automated manufacturing of wind turbine blade spar caps (grade: 1.0). This project was part of the BladMaker project at Fraunhofer IWES."

	    [[params.projects.list]]
	    title = "Student Research Project"
	    url = "https://www.mv.uni-kl.de/en/sam/"
	    tagline = "Designed and manufactured a scaled model of an Audi R8 for wind tunnel testing. Simulated aerodynamic reference CFD model for validation (grade 1.0). This project was supervised by the Institute of Fluid Mechanics and Turbomachinery at the Technical University of Kaiserslautern."
		#I deepened my CAD design and CFD expertise and gained practical experience in wind tunnel operation.
	
	    [[params.projects.list]]
	    title = "Student Research Project:"
	    url = "https://www.mv.uni-kl.de/en/imad/"
	    tagline = "Numerically investigated the impact of compressibility on high-pressure water jet cutting by implementing a user-defined function into a CFD model and evaluating the impact of various model parameters (grade 1.0).  This project was supervised by the Institute for Mechanical and Automotive Design at the Technical University of Kaiserslautern."

# Skills section

[params.skills]
    enable = true
    icon = "fa-rocket"
    title = "Skills & Proficiency"

    [[params.skills.list]]
    skill = "Wind Energy"
    level = "100%"
	
	[[params.skills.list]]
    skill = "Mechanical Design"
    level = "80%"

    [[params.skills.list]]
    skill = "Aerodynamics"
    level = "90%"
	
	[[params.skills.list]]
    skill = "Project Management"
    level = "80%"
	
	[[params.skills.list]]
    skill = "Testing & Certification"
    level = "70%"
	
	[[params.skills.list]]
    skill = "Data Analysis"
    level = "90%"
	
	[[params.skills.list]]
    skill = "Fundamental fluid and solid mechanics"
    level = "90%"
						 
    [[params.skills.list]]
    skill = "Python & Matlab"
    level = "90%"
            
    [[params.skills.list]]
    skill = "CAD software: Catia, Solid Edge"
    level = "80%"

    [[params.skills.list]]
    skill = "CFD: ANSYS Fluent"
    level = "80%"

    [[params.skills.list]]
    skill = "FEA: ANSYS Mechanical"
    level = "50%"

    [[params.skills.list]]
    skill = "Mesoscale weather modeling: WRF"
    level = "70%"
	
	[[params.skills.list]]
    skill = "Budgeting"
    level = "50%"



# Soft Skills section

[params.softskills]
    enable = true
    icon = "fa-commenting"
    title = "Personal Skills"

	[[params.softskills.list]]
    skill = "Self-Management"
    level = "100%"
		
	[[params.softskills.list]]
    skill = "Teamwork"
    level = "80%"
	
	[[params.softskills.list]]
    skill = "Creativity"
    level = "80%"
	
	[[params.softskills.list]]
    skill = "Problem Solving"
    level = "100%"
		
	[[params.softskills.list]]
    skill = "Proactive"
    level = "90%"
	
	[[params.softskills.list]]
    skill = "Public Speaking"
    level = "90%"

	[[params.softskills.list]]
    skill = "Communication"
    level = "80%"
	
	[[params.softskills.list]]
    skill = "Critical Thinking"
    level = "80%"
	
	[[params.softskills.list]]
    skill = "Adaptability"
    level = "100%"


	# Publication section
		[params.publications]
		enable = true
		icon = "fa-newspaper-o"
		title = "Publications"
		intro = ""
		
		[[params.publications.list]]
		title = "Ground-generation airborne wind energy design space exploration"
		url = "https://doi.org/placeholder"
		tagline = "Wind Energy Science, Submitted"
		
		[[params.publications.list]]
		title = "Offshore and onshore ground-generation airborne wind energy power curve characterization"
		url = "https://doi.org/placeholder"
		tagline = "Wind Energy Science, Submitted"
		
		[[params.publications.list]]
		title = "Airborne wind energy trajectory optimization using realistic wind speed profiles"
		url = "https://doi.org/10.5281/zenodo.3357152"
		tagline = "Wind Energy Science Conference 2019"
		
		[[params.publications.list]]
		title = "Mesoscale model based techniques for LiDAR wind speed measurement gap-filling"
		url = "https://doi.org/10.5281/zenodo.3357147"
		tagline = "Wind Energy Science Conference 2019"

		[[params.publications.list]]
		title = "Parametric AWES Sizing Study Using Mesoscale Wind Profiles"
		url = "https://doi.org/10.4233/uuid:57fd203c-e069-11e9-9fcb-441ea15f7c9c"
		tagline = "Airborne Wind Energy Conference 2019"
		
		[[params.publications.list]]
		title = "Coupled Kite-Ground Station Simulink Model for Optimal FlightPath Following Assessment"
		url = "https://doi.org/10.4233/uuid:57fd203c-e069-11e9-9fcb-441ea15f7c9c"
		tagline = "Airborne Wind Energy Conference 2019"
	  
		[[params.publications.list]]
		title = "Improving mesoscale wind speed forecasts using lidar-based observation nudging for airborne wind energy systems"
		url = "https://doi.org/10.5194/wes-4-563-2019"
		tagline = "Wind Energy Science, Volume 4, Issue 4, October 2019"

		[[params.publications.list]]
		title = "LiDAR-based characterization of mid-altitude wind conditions for airborne wind energy systems"
		url = "https://doi.org/10.1002/we.2343"
		tagline = "Wiley Wind Energy: Volume22, Issue 8, August 2019"

		[[params.publications.list]]
		title = "High Altitude LiDAR Measurements of the Wind Conditions for Airborne Wind Energy Systems"
		url = "http://www.awec2017.com/presentations/markus-sommerfeld"
		tagline = "Airborne Wind Energy Conference 2017"

		[[params.publications.list]]
		title = "LES generated turbulent inflow fields from mesoscale modeling driven by LiDAR measurements"
		url = "http://www.awec2017.com/presentations/markus-sommerfeld-2"
		tagline = "Airborne Wind Energy Conference 2017"

		[[params.publications.list]]
		title = "AWESome potential: Airborne wind energy’s opportunities and challenges"
		url = "https://youtu.be/UiriQHZMcs0"
		tagline = "Pacific Institute for Climate Solutions, March 2018"




# Presentation section

#[params.presentations]
#enable = true
#icon = "fa-presentation"
#title = "Presentations"
#intro = "**You can list your side projects or open source libraries in this section.** Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum et ligula in nunc bibendum fringilla a eu lectus"
#
#[[params.presentations.list]]

#    title = "Hugrid"

#    url = "https://github.com/aerohub/hugrid"

#    tagline = "Grid theme for Hugo. It's a kind of boilerplate to perform anyone or anything quickly. Portfolio, collection, bookmarks, contacts and so on"



	 

# Footer section


# The original template is released under the Creative Commons Attribution 3.0 License.

# Please keep the original attribution link when using for your own project.

# If you'd like to use the template without the attribution,

# you can check out other license options via template author's website: themes.3rdwavemedia.com

# 

# As for Hugo port you may rewrite the "Ported for..." line with setting your name below.

[params.footer]
    copyright = "Markus Sommerfeld"


